name: Build and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1
      
    - name: Install and Build 🔧
      run: |
        npm install
        npm run build
      env:
        REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
    
    # - name: Test ✅
    #   run: |
    #     npm run test
